name = "newsnow"
pages_build_output_dir = "dist/output/public"
compatibility_date = "2024-10-28"

[vars]
G_CLIENT_ID = "Ov23liUfqJYEHSLOcmTO"
G_CLIENT_SECRET = "38271f5b10ec2f1c3d2734a5ba564094a9d1d324"
JWT_SECRET = "38271f5b10ec2f1c3d2734a5ba564094a9d1d324"

[[d1_databases]]
binding = "NEWSNOW_DB"
database_name = "newsnow"
database_id = "63cd1383-de95-47b3-b147-deb3f57bb3e9"
